### ISSUE TITLE
Misspellings

### ISSUE THREAD

**Issue by d-g-h** [bradfrost/frontend-guidelines-questionnaire#1]
https://github.com/bradfrost/frontend-guidelines-questionnaire/blame/4ec5505c074df6b72a36dc78c1a2688d7824e0be/README.md#L2

~~guidlines~~ guidelines

https://github.com/bradfrost/frontend-guidelines-questionnaire/blame/4ec5505c074df6b72a36dc78c1a2688d7824e0be/README.md#L31

~~insipration~~ inspiration

https://github.com/bradfrost/frontend-guidelines-questionnaire/blame/4ec5505c074df6b72a36dc78c1a2688d7824e0be/README.md#L34

~~crtical~~ critical

Thanks for doing this. I hope to use this somewhere soon.

**Comment by bradfrost** [comment]
@d-g-h Thanks for the keen eyes, in more ways than one! I'm planning on releasing this tomorrow.
