### ISSUE TITLE
Website page speed measuring?

### ISSUE THREAD

**Issue by brianmontanaweb** [bradfrost/frontend-guidelines-questionnaire#2]
"Do you have performance budgets? How do you implement it? What guidelines do you follow to reduce the site's render time?"

Something along those lines, I've asked new teams that and on contract projects. Answers are surprisingly no :(

**Comment by bmuenzenmeyer** [comment]
:+1: to this.

I was fortunate enough to hear Tim Kadlec speak on this topic. Some relevant notes here: https://gist.github.com/bmuenzenmeyer/e40f19855e9037e09d50#performance-budget 

My favorite part is that the distinction between the differing types of budget metrics and how they align against user perception.

Hope this helps! Great idea Brad!

**Comment by bradfrost** [comment]
@brianmontanaweb yeah that's a great addition. I was thinking performance questions would be baked into the other sections, such as CSS (crit CSS) and tooling (performance budget stuff). But yeah I think it could be elevated as its own category.

**Comment by brianmontanaweb** [comment]
@bradfrost Awesome, I'll do a pull request with some general questions I've asked teams about website performance with references, using the same writing style.

@bmuenzenmeyer Thanks, I'll watch that too :+1:
